# French for every unit in units_en.json that is more than numbers, keyed by unit id. Written with
# plain spaces before ":" and ";" and between numbers and units; build_fr.py turns those into
# non-breaking spaces. Numbers-only units ("48.2 × 11", "7.55 m²") need no entry: they get decimal
# commas automatically. {DATE} stands for generate.py's date stamp, spelled in French at build time.

FR = {
    0: "Console DJ et piano, dossier technique",
    1: "Console DJ et piano",
    3: "Un meuble d’un seul tenant, de 185 cm de large, qui accueille une installation DJ sur le dessus à hauteur debout, un piano de scène sur une tablette coulissante à hauteur assise, environ 160 disques dans deux colonnes d’extrémité, des livres dans deux compartiments ouverts, deux tiroirs encadrant une niche d’alimentation, et deux enceintes de monitoring sur des chapeaux en haut des colonnes. La travée centrale flotte à 20 cm au-dessus du sol, pour laisser la place à une pédale de sustain et aux pieds.",
    4: "Cotes principales",
    5: "Élément",
    6: "Valeur",
    7: "Encombrement",
    8: "185 de large × 50 de profondeur × 130 de haut (chapeaux). Surface DJ à 100. L’emprise est la même à toutes les hauteurs : les chapeaux affleurent les colonnes.",
    9: "Travée (entre les colonnes)",
    10: "145 de large. Emprise du matériel 145 ; tablette de clavier 141,2 hors tout, rebords compris ; clavier 133.",
    11: "Colonnes",
    12: "20 de large chacune, 16,4 libres à l’intérieur, pleine hauteur jusqu’à 127, chapeau de 20 × 50 × 3 au sommet.",
    13: "Tablette de clavier",
    14: "Face supérieure 63 ; face inférieure 61,2 ; sortie 40 ; tablette 137,6 × 42. Dessus des touches à environ 74 (hauteur d’un piano).",
    15: "Dégagement",
    16: "20 libres, sur toute la largeur de la travée, ouvert jusqu’au mur.",
    17: "Répartition de la profondeur",
    18: "48,2 utiles dans la travée, panneau arrière de 1,8 à fleur de la face arrière. Traverse avant 5 ; logement le plus profond 36,2 ; traverse arrière 7,0. Les colonnes utilisent toute la profondeur (48,2 à l’intérieur).",
    19: "Écart au mur",
    20: "5 derrière le panneau arrière, obligatoire : le panneau s’arrête à 91 et tout l’arrière de la goulotte est ouvert, elle se ventile par cet écart. Prévoir 55 de profondeur au sol, et non 50. Coté sur la coupe et sur la vue en plan.",
    21: "Épaisseur des panneaux",
    22: "Caisson 18 mm, plateau et chapeaux 30 mm au-dessus d’un bandeau de 60 mm, corps de tiroir 15 mm.",
    23: "Rangement",
    24: "Environ 160 disques dans les colonnes (six casiers, 6 mm par pochette ; 190 si ce sont surtout des pochettes simples), deux compartiments à livres de 71,6 cm, deux tiroirs. Chaque compartiment à livres peut recevoir environ 110 vinyles de plus si besoin.",
    25: "Poids à vide",
    26: "Environ 120 à 130 kg. Environ 250 kg une fois chargé de disques, de livres et du matériel. Réparti sur les deux colonnes et la travée flottante.",
    27: "Organisation des zones",
    28: "Zone",
    29: "Hauteur (cm)",
    30: "Contenu",
    31: "Chapeaux d’enceintes",
    32: "127 à 130",
    33: "Deux enceintes de monitoring de 5 pouces sur patins de découplage, une par colonne. Chapeau de 20 × 50 cm, chêne 30 mm, à fleur de la colonne sur toutes ses faces. Une KRK Rokit 5 (18,5 de large) laisse 7 mm de chaque côté.",
    34: "Surface DJ",
    35: "100 (plateau de 91 à 100)",
    36: "Platine vinyle, XDJ-700, Xone:92, XDJ-700 de gauche à droite dans la travée de 145 cm, chacun encastré dans un logement qui offre 9 cm de hauteur libre mesurée sous sa plaque supérieure, et non par rapport à sa hauteur hors tout. Les plaques supérieures arrivent à fleur du chêne. Traverse avant 5 cm, ponts de chêne d’environ 5,6 cm. Les capots anti-poussière ne peuvent pas être montés.",
    37: "Zone des tiroirs",
    38: "80 à 89,2 (façades jusqu’à 91)",
    39: "Deux tiroirs à fleur, de 58,7 cm (9,2 cm de haut), encadrant une niche d’alimentation de 24 cm : porte à ouverture par pression, multiprise et blocs d’alimentation à l’intérieur, ouverte en haut sur la goulotte à câbles.",
    40: "Goulotte à câbles",
    41: "91 à 97",
    42: "Continue sous la traverse arrière, sur toute la travée de 145 cm, 7 cm de profondeur derrière la Xone:92 et 12,2 derrière les XDJ. Chaque logement s’y ouvre. Sa face arrière est ouverte elle aussi, 145 × 6 cm, de sorte que l’air entre et sort sur toute sa longueur par l’écart de 5 cm au mur ; c’est aussi la ventilation de la table de mixage.",
    43: "Emplacement du clavier",
    44: "63 à 78,2",
    45: "Tablette coulissante, face supérieure à 63 cm, sortie de 40 cm sur coulisses forte charge. Clavier de 133 × 35 × 12 rangé à l’intérieur, avec 3,2 cm d’air au-dessus.",
    46: "Compartiments à livres",
    47: "21,8 à 61,2",
    48: "Deux ouvertures de 71,6 de large × 39,4 de haut × 33,2 de profondeur, une étagère réglable chacune. Plan avant en retrait de 15 cm par rapport à la face de la console, pour dégager les tibias en position assise. Accepte toujours une pochette de vinyle de 31,4 cm, avec 1,8 cm de marge.",
    49: "0 à 20 (jusqu’à 61,2 à l’avant)",
    50: "Ouvert sur toute la travée et jusqu’au mur : pédale de sustain et pieds en position assise, place pour la pointe des pieds en position debout. Les 15 cm avant restent ouverts jusqu’à la face inférieure de la tablette, pour que les tibias ne touchent pas les étagères.",
    51: "Colonnes latérales",
    52: "7,8 à 127",
    53: "Trois casiers par colonne, 16,4 de large × 38,5 de haut × 48,2 de profondeur, disques rangés tranche visible, environ 27 par casier à 6 mm chacun, environ 160 au total.",
    54: "Ergonomie",
    55: "Assis au clavier : avec la tablette à 63 cm, le dessus des touches se trouve à environ 74 cm, comme sur un piano acoustique. La hauteur libre sous la tablette est de 61,2 cm ; prévoir un tabouret de 44 à 46 cm. La tablette sort de 40 cm : les genoux se placent sous la tablette, les pieds et la pédale vont dans le dégagement de 20 cm. Rien ne dépasse sous la tablette à l’avant. La zone des livres est en retrait de 15 cm par rapport au plan avant, les tibias passent donc sans la toucher ; en v1, ils passaient à environ 1 cm du chant avant du panneau bas.",
    56: "Debout aux platines : surface à 100 cm, toutes les plaques supérieures à fleur. La pointe des pieds passe sous la travée flottante. Pour atteindre une prise arrière dans un logement, il faut sortir l’appareil en le soulevant par les encoches de préhension du logement.",
    57: "Enceintes : avec le dessus des chapeaux à 130 cm, le tweeter d’une enceinte de 5 pouces se trouve à environ 152 cm, un peu sous la hauteur des oreilles en position debout ; les patins de découplage ajoutent une légère inclinaison vers le haut. Les orienter vers le centre.",
    58: "Câblage : les câbles de chaque lecteur sortent par l’entaille de 12 cm de la paroi arrière de son logement, vers la goulotte sous la traverse arrière ; le logement de la Xone:92 n’a pas de paroi arrière et s’ouvre sur la goulotte sur toute sa largeur. Les câbles suivent la goulotte et descendent dans la niche d’alimentation, où se trouvent la multiprise à interrupteur et les blocs d’alimentation. Le câble secteur du clavier et le câble de la pédale conservent leur découpe derrière la tablette ; laisser une boucle de 60 cm de mou pour la course de la tablette. Placer la console à 5 cm du mur : le panneau arrière forme la face arrière et s’arrête à 91, l’arrière de la goulotte est donc ouvert sur toute la travée, et c’est cet écart qui permet à l’air d’y circuler et aux câbles d’en sortir.",
    59: "Implantation du matériel dans le plateau",
    60: "Appareil",
    61: "L × P × H hors tout (cm)",
    62: "Hauteur sous la plaque supérieure (cm), 9 au maximum",
    63: "Position depuis la face intérieure de la colonne gauche (cm)",
    64: "Platine vinyle",
    66: "à mesurer sur l’appareil",
    67: "3 à 48,3",
    68: "XDJ-700",
    70: "54,3 à 76,1",
    71: "Xone:92",
    73: "82,1 à 114,1",
    74: "120,1 à 141,9",
    75: "Les positions supposent une platine au format Technics (45,3 × 35,3), une Allen &amp; Heath Xone:92 et deux Pioneer XDJ-700, avec des intervalles de 6 cm et des marges de 3 cm aux extrémités. Remesurer les appareils réels avant toute découpe : chaque logement est réalisé au gabarit de son appareil avec seulement 2 mm de jeu par côté, les découpes en dépendent donc directement. La colonne H donne la hauteur <strong>hors tout</strong> de chaque appareil, tout compris : les 16,2 de la platine correspondent surtout à son capot anti-poussière, qui ne peut plus être monté une fois la platine encastrée. Ce n’est pas la hauteur hors tout que le logement doit absorber. Le logement offre 9 cm de hauteur libre <strong>sous la plaque supérieure</strong>, de la ligne des plaques à 100 jusqu’au fond du logement à 91, et c’est la hauteur du châssis de chaque appareil sous sa propre plaque supérieure qui doit y tenir. La mesurer sur les quatre appareils avant la découpe ; les tasseaux des fonds de logement rattrapent ensuite la différence, mais seulement de ±10 mm.",
    76: "Variantes encore ouvertes",
    77: "Chapeaux d’enceintes : le chapeau précédent de 24 cm, débordant de 4 cm vers l’intérieur, a été abandonné le 14 septembre 2026 ; un chapeau affleurant de 20 cm suffit pour une KRK Rokit 5. N’élargir le chapeau que si les enceintes changent.",
    78: "Capacité en disques : colonnes élargies de 14,5 à 20 cm le 14 septembre 2026 (185 cm hors tout), environ 160 disques à 6 mm par pochette. Chaque compartiment à livres peut recevoir environ 110 vinyles de plus si besoin.",
    79: "Étagère murale pour les enceintes plus tard : on peut supprimer les chapeaux et arrêter les colonnes à 100 cm, ce qui fait du meuble un simple caisson de 185 × 100.",
    80: "1. Élévation de face",
    81: "disques, tranche visible",
    82: "zone des livres en retrait de 15 cm pour dégager genoux et tibias",
    83: "niche d’alimentation",
    84: "appareils en pointillés : encastrés sous la surface, cachés derrière le bandeau dans cette vue",
    85: "Matériel encastré de 9 cm : plaques à fleur dans un chêne continu, logements ouverts sur la goulotte, sans capots anti-poussière",
    86: "Tiroir : câbles, adaptateurs, diamants",
    87: "Tiroir : casques",
    88: "façade de 11 cm sur un corps de 9,2 cm",
    89: "Clavier 133 × 35 × 12 rangé sur la tablette coulissante (sortie 40 cm, voir coupe)",
    90: "Livres ou vinyles (39 cm libres)",
    91: "Étagère réglable sur taquets de 5 mm",
    92: "Dégagement pour les pieds et la pédale, 20 cm libres, toute la largeur, ouvert jusqu’au mur",
    93: "crochet à casque (extérieur)",
    94: "enceintes 5&quot; sur patins de découplage",
    96: "145 travée / emprise du matériel",
    97: "185 hors tout (emprise = largeur à toutes les hauteurs)",
    100: "11 façades",
    101: "9 plateau",
    103: "63 dessus tablette",
    104: "100 surface DJ",
    105: "130 dessus chapeau",
    108: "panneaux 18 mm, plateau et chapeaux 30 mm",
    109: "2. Coupe latérale de la travée, passant par la niche d’alimentation et la table de mixage, vue vers la colonne droite",
    110: "colonne droite (en arrière-plan)",
    111: "mur",
    112: "écart de 5 cm au mur, obligatoire : la goulotte s’aère et le câble secteur sort ici",
    113: "goulotte",
    114: "15 retrait",
    115: "tabouret 44 à 46 cm",
    116: "la cuisse passe sous la tablette (61,2)",
    117: "goulotte à câbles sous la traverse arrière, 7 cm de profondeur, arrière ouvert",
    118: "panneau arrière 18 mm, à fleur de la face arrière, chant supérieur à 91",
    119: "niche d’alimentation : multiprise à plat, blocs posés à l’arrière",
    120: "panneau arrière découpé derrière la niche",
    121: "coulisse de tablette forte charge 400 mm (détail A)",
    122: "pédale de sustain dans le dégagement",
    123: "tablette sortie de 40 cm (pointillés)",
    124: "48,2 intérieur",
    125: "5 écart au mur",
    126: "5 traverse avant",
    127: "7 traverse arrière",
    128: "50 profondeur hors tout",
    129: "40 sortie",
    130: "42 tablette",
    131: "20 dégagement",
    133: "61,2 libres sous la tablette",
    135: "3. Vue en plan du plateau",
    136: "enceinte 5&quot;",
    137: "découpe 45,7 × 35,7",
    138: "découpe 22,2 × 31",
    139: "découpe 32,4 × 36,2",
    140: "goulotte à câbles, toute la travée",
    141: "panneau arrière (en dessous) arrêté à 91 : la face arrière de la goulotte est ouverte sur toute la travée, 145 × 6 cm, et se ventile dans l’écart au mur",
    145: "crochet à casque",
    154: "36,2 logement le plus profond",
    156: "4. Détail A : chant de la tablette, coulisse et rebord (coupe vue de face, côté gauche)",
    157: "compartiment à livres en dessous",
    158: "colonne latérale",
    162: "12 clavier",
    164: "Panneau fixe 18 mm de 78,2 à 80 ; zone des tiroirs au-dessus",
    165: "Coulisse forte charge 400 mm, 100 kg ou plus par paire, blocage en position ouverte",
    166: "Rebord en chêne massif 18 × 68 mm sur le chant de la tablette ; la coulisse s’y visse",
    167: "Clavier de 133 de large, 2,3 cm de chaque rebord, dessus des touches à environ 74",
    168: "Fin tapis antidérapant sous le clavier",
    169: "Tablette en contreplaqué bouleau plaqué chêne 18 mm, 137,6 × 42, finie sur les deux faces",
    170: "Panneau intérieur de colonne 18 mm = paroi latérale de la travée ; reçoit la partie fixe de la coulisse",
    171: "5. Détail B : logement d’appareil (coupe à travers la traverse avant)",
    172: "9 libres",
    174: "Plateau en chêne 30 mm ; arêtes des découpes adoucies, sans alaise",
    175: "Bandeau en chêne massif 60 mm, en façade et aux extrémités ; chant inférieur à 91, au niveau des fonds de logement",
    176: "Les plaques supérieures de la Xone:92 et des XDJ-700 peuvent reposer sur une feuillure ; vérifier sur les appareils",
    177: "Plaque supérieure à fleur du chêne ; 2 mm de jeu sur les côtés et à l’arrière, aucun à l’avant. Ne pas boucher ce jeu",
    178: "Le socle de la Technics est sans collerette : elle repose sur ses propres pieds, sur le fond à 91",
    179: "Fond de logement 18 mm sur tasseaux à trous oblongs, ±10 mm : dessus à 91, dessous à 89,2",
    180: "Tasseau 20 × 14 mm, deux par logement, d’avant en arrière ; face supérieure à fleur sous le fond",
    181: "Logements des lecteurs : paroi arrière entaillée sur 12 cm de large vers la goulotte ; la Xone:92 n’a pas de paroi arrière",
    182: "encoches de préhension à deux coins de chaque logement, r 20 mm",
    183: "Nomenclature",
    184: "Groupe",
    185: "Pièce",
    186: "Qté",
    187: "Dim. L × l (cm)",
    188: "Ép. (mm)",
    189: "Matériau",
    190: "Remarques",
    191: "Joue de colonne",
    195: "Contreplaqué bouleau plaqué chêne, chant avant alaisé",
    196: "Du sol jusqu’à la face inférieure du chapeau. La paire intérieure forme aussi les parois latérales de la travée. Fil vertical.",
    197: "Étagère basse de colonne",
    200: "Contreplaqué plaqué chêne",
    201: "Face supérieure à 7,8 cm (plinthe de 6 cm en dessous).",
    202: "Étagère fixe de colonne",
    203: "Contreplaqué plaqué chêne, chant avant alaisé",
    204: "Deux par colonne, formant trois casiers de 38,5 cm libres.",
    205: "Panneau arrière de colonne",
    207: "À fleur du chant arrière (pas de gaine technique dans les colonnes).",
    208: "Plinthe de colonne",
    210: "Chêne massif",
    211: "En retrait de 3 cm par rapport à l’avant.",
    212: "Chapeau d’enceinte",
    214: "Même emprise que la colonne, à fleur sur toutes les faces. Vissé par en dessous à travers les joues de colonne.",
    215: "Travée",
    216: "Plateau",
    219: "Chêne massif, ou panneau plaqué 30 mm avec alaise en chêne de 30 mm",
    220: "Quatre découpes pour le matériel, avec tous les bords avant à 5 cm du chant avant. Dimensions selon la vue en plan ; 2 mm de jeu sur les côtés et à l’arrière, aucun à l’avant. Encoches de préhension r 20 mm à deux coins de chacune. Arêtes adoucies, sans alaise.",
    221: "Bandeau du plateau",
    224: "Face avant, en retour aux deux extrémités. Chant inférieur à 91, à fleur des fonds de logement. Donne visuellement au plateau une épaisseur de 9 cm.",
    225: "Paroi latérale de logement",
    227: "7,8 de haut, profondeur selon le logement",
    228: "Deux par logement, suspendues sous le plateau jusqu’à 89,2, soit la face inférieure du fond de logement : les 18 mm inférieurs de chaque paroi reçoivent le fond et portent son tasseau. Collées au plateau : c’est ce qui rigidifie les ponts entre les logements. Profondeur par logement : platine 35,7 ; XDJ-700 31 ; Xone:92 36,2 ; XDJ-700 31 cm. Voir la coupe du détail B (plan 5).",
    229: "Paroi arrière de logement",
    230: "6 de haut, largeur selon le logement",
    231: "Une par logement de lecteur uniquement : la platine et les deux XDJ-700. Chacune reçoit une entaille de 12 × 6 cm pour les câbles. L’entaille fait 12 cm de large, elle est centrée sur le logement et va du fond du logement à 91 jusqu’au plateau, pour qu’une fiche passe sans avoir à être soulevée. Le logement de la Xone:92 n’a aucune paroi arrière : toute sa face arrière, 32,4 × 6 cm, est ouverte sur la goulotte, et c’est ainsi que la table de mixage évacue sa chaleur. Largeur par paroi : platine 45,7 ; XDJ-700 22,2 ; XDJ-700 22,2 cm. Voir la coupe du détail B (plan 5).",
    232: "Fond de logement",
    233: "largeur × profondeur selon le logement",
    234: "Face supérieure à 91, face inférieure à 89,2 (le plafond de la zone des tiroirs). Sur tasseaux réglables à trous oblongs de ±10 mm, pour régler l’affleurement sur les appareils réels lors de l’installation. Largeur × profondeur par logement : platine 45,7 × 35,7 ; XDJ-700 22,2 × 31 ; Xone:92 32,4 × 36,2 ; XDJ-700 22,2 × 31 cm. Voir la coupe du détail B (plan 5).",
    235: "Tasseau de fond de logement",
    236: "20 × 14 mm, longueur selon le logement",
    237: "Deux par logement, d’avant en arrière sur les parois latérales, trous de vis oblongs. Face supérieure à 89,2, pour que le fond arrive à 91 sans que rien ne dépasse. Longueur par logement : platine 35,7 ; XDJ-700 31 ; Xone:92 36,2 ; XDJ-700 31 cm. Voir la coupe du détail B (plan 5).",
    238: "Panneau bas de la travée",
    240: "Face supérieure à 21,8 cm. Chant avant en retrait de 15 cm par rapport au plan avant, pour dégager les tibias ; le dégagement est donc ouvert du sol jusqu’à la face inférieure de la tablette sur ces 15 cm. Porte les livres ; rigidifié par la séparation et le panneau arrière, sans traverse en dessous.",
    241: "Panneau fixe intermédiaire",
    243: "Face supérieure à 80 cm. Plafond de l’emplacement du clavier, plancher de la zone des tiroirs.",
    244: "Panneau arrière de la travée",
    246: "À fleur de la face arrière, chant supérieur à 91 : il n’y a aucun panneau au-dessus, la face arrière de la goulotte est donc ouverte sur toute la travée, 145 × 6 cm. C’est par cette ouverture que la goulotte respire et que les câbles sortent. Découpe de 20 × 8 cm derrière la tablette, de 66 à 74 cm ; découpe de 24 × 8 cm derrière la niche, de 83 à 91 cm. La découpe de la niche débouche sur le chant supérieur du panneau, là où la goulotte ouverte prend le relais.",
    247: "Séparation de la zone des livres",
    249: "Centrée. Collée et vissée au panneau bas et au panneau arrière sur toute sa longueur ; jeu de 5 mm sous la tablette.",
    250: "Séparation de la zone des tiroirs",
    252: "Encadrent la niche d’alimentation de 24 cm. Entaillées : les 5 cm avant montent à 11 cm avec les façades et ferment la bande située derrière les jeux entre les façades ; au-delà, elles redescendent à 9,2 cm pour passer sous les fonds de logement. Passage optionnel de 6 × 4 cm à l’arrière de chacune pour un câble de recharge.",
    253: "Porte de la niche d’alimentation",
    255: "Chêne massif, fil continu avec les façades de tiroir",
    256: "Rentrante à fleur, charnières invisibles, ouverture par pression. 9,8 cm dans l’ouverture de 11 cm : le jeu de ventilation de 1 cm est entièrement pris au chant inférieur, de sorte que le chant supérieur rejoint toujours le bandeau à 91.",
    257: "Étagère réglable",
    259: "Une par compartiment à livres, sur taquets de 5 mm.",
    260: "Façade de tiroir",
    262: "Chêne massif (fil continu sur les deux façades)",
    263: "Rentrante à fleur, jeux de 2 mm, prise de main fraisée sous le chant supérieur. 11 cm sur un corps de 9,2 cm : elle dépasse le corps de 18 mm vers le haut pour rejoindre le bandeau à 91 et fermer la face avant. Dégagée à l’arrière, car les fonds de logement commencent 5 cm en retrait. Dimensionner d’après l’ouverture, pas d’après le corps.",
    264: "Corps de tiroir",
    265: "45 de profondeur × 7 de haut, largeur selon la notice des coulisses",
    267: "Contreplaqué bouleau, fond 6 mm",
    268: "Pour les ouvertures de 58,7 cm, dimensionné selon les coulisses. La profondeur de 45 cm correspond à des coulisses sous tiroir de 450 mm : une paire de coulisses sous tiroir ne s’engage que sur un corps de sa propre longueur, les coulisses de 400 mm utilisées en v1 ne conviennent donc pas. Des côtés de 7 cm dans la zone de 9,2 cm laissent 22 mm sous et au-dessus du corps pour la coulisse et ses jeux. Vérifier sur le plan de perçage du fabricant de la coulisse avant de découper. Entailler la paroi côté niche de 6 × 4 cm à l’arrière si le passage de câble est utilisé.",
    269: "Tablette",
    270: "Panneau de la tablette de clavier",
    272: "Contreplaqué bouleau plaqué chêne deux faces",
    273: "La face inférieure est visible depuis les compartiments à livres : la finir. Chant avant alaisé.",
    274: "Rebord latéral de tablette",
    276: "Couvre le chant de la tablette (1,8) et le dépasse de 5 cm vers le haut. La partie mobile de la coulisse s’y visse.",
    277: "Traverse arrière de tablette",
    279: "Sur le dessus de la tablette, le long du chant arrière, tourillonnée aux rebords. Empêche la déformation en parallélogramme.",
    280: "Tous",
    281: "Alaise en chêne massif",
    282: "env. 28 m",
    283: "5 × 18 mm",
    285: "Tous les chants de contreplaqué apparents.",
    286: "Quincaillerie",
    287: "Spécification",
    288: "Coulisses de la tablette de clavier",
    289: "1 paire",
    290: "Coulisses à billes forte charge à sortie totale, 400 mm, charge nominale de 100 kg ou plus par paire, avec blocage en position ouverte. Accuride 3634 (400 mm) ou Fulterer FR 5000 (400 mm). Montage latéral entre 63 et 68 cm.",
    291: "Coulisses de tiroir",
    292: "2 paires",
    293: "Coulisses sous tiroir à sortie totale avec fermeture amortie, 450 mm, classe 40 kg : Blum Movento 760H4500S avec Blumotion, ou Hettich Actro 5D 450 mm. Pas la paire de 400 mm utilisée en v1 : une coulisse sous tiroir est adaptée à son corps de tiroir, et un corps de 45 cm ne s’engage pas sur une coulisse de 400 mm. Vérifié par rapport à l’intérieur : une coulisse de 450 mm demande environ 470 mm de profondeur libre et la travée offre 482 mm, elle tient donc avec environ 12 mm de marge.",
    294: "Taquets d’étagère",
    295: "Acier 5 mm, deux étagères réglables. Entraxe de 32 mm ; rangées à 18,7 et 44,5 cm en retrait de la face avant de la console, à 37 mm des faces du compartiment.",
    296: "Pieds de réglage",
    297: "Vérins réglables M8, 15 à 25 mm, deux par joue de colonne, cachés derrière les plinthes.",
    298: "Équerres anti-basculement",
    299: "Une par colonne, invisible, fixée au mur. Recommandé : les colonnes font 130 cm de haut avec des enceintes au sommet. En v2, elle sert aussi d’entretoise : la caler à 5 cm pour qu’elle maintienne la console à cette distance du mur au lieu de la plaquer contre lui. L’arrière ouvert de la goulotte se ventile dans cet écart ; le fermer couperait la ventilation de la table de mixage.",
    300: "Patins de découplage d’enceintes",
    301: "IsoAcoustics ISO-155 ou Auralex MoPAD, réglés avec une légère inclinaison vers le haut, en direction de la position debout.",
    302: "Crochet à casque",
    303: "Acier noir ou chêne, sur la face extérieure de la colonne droite, à environ 105 cm.",
    304: "Multiprise",
    305: "6 prises avec interrupteur, 40 cm de long au maximum, ou deux multiprises de 4 prises côte à côte. Posée à plat sur le fond de la niche, prises vers le haut. La niche mesure 24 de large × 9,2 de haut × 48,2 de profondeur ; ses 7 cm arrière sont ouverts en haut sur la goulotte à câbles, le reste est couvert par les fonds de logement. Poser les blocs d’alimentation sur le fond de la niche à côté de la multiprise, vers l’arrière, entre 41,2 et 48,2 cm de l’avant, au-delà du point où s’arrêtent les fonds de logement. À cet endroit, la goulotte est ouverte au-dessus et la hauteur libre est de 17 cm, jusqu’à la face inférieure de la traverse arrière, à 97 : la hauteur des blocs n’y est donc pas une contrainte. Ne pas empiler de bloc sur la multiprise : l’ensemble atteint environ 12,5 cm au-dessus du fond de la niche, soit 92,5, ce qui bute contre le fond de logement si le bloc est vers l’avant de la niche et bouche la goulotte s’il est à l’arrière. Or la goulotte doit rester dégagée, car c’est le chemin du câble secteur qui sort par la découpe de la niche, de 83 à 91 cm. La hauteur ne compte que si un bloc doit être placé à l’avant de la niche, sous un fond de logement : il y a là 9,2 cm de hauteur libre, qu’un bloc de 8,5 cm franchit avec 7 mm de marge.",
    306: "Quincaillerie de la porte de niche",
    307: "1 jeu",
    308: "Deux charnières invisibles (Blum Clip top ou équivalent) et un système d’ouverture par pression (Blum Tip-On) : pas de poignée. Son jeu de ventilation de 1 cm se place au chant inférieur.",
    309: "Passe-câbles des tiroirs",
    310: "2 (en option)",
    311: "Passe-câbles de 60 × 40 mm en caoutchouc ou garnis de chêne dans les séparations de la zone des tiroirs, pour les câbles de recharge allant de la multiprise aux tiroirs.",
    312: "Tapis antidérapant",
    313: "Feuille fine de caoutchouc ou d’EVA, environ 133 × 35 cm, sous le clavier.",
    314: "Fixations du caisson",
    315: "selon besoin",
    316: "Tourillons de 8 mm et colle à tous les assemblages visibles ; vis Confirmat là où elles restent cachées (derrière les tiroirs et la tablette). Vis des coulisses selon le fabricant.",
    317: "Finition",
    318: "environ 1 L",
    319: "Osmo Polyx-Oil 3062 Matt, deux couches, ou Rubio Monocoat Oil Plus 2C Pure (environ 350 ml). Ton chêne naturel, sans teinture.",
    320: "Tasseaux et fixations des fonds de logement",
    321: "8 tasseaux",
    322: "Inserts filetés M5 et vis à tête cylindrique dans des trous oblongs, ±10 mm de course, pour que l’affleurement de chaque appareil se règle à l’installation plutôt qu’à la découpe.",
    323: "Matériaux et finition",
    324: "Caisson : contreplaqué bouleau plaqué chêne 18 mm, placage tranché sur dosse qualité A/B, chaque chant apparent alaisé en chêne massif de 5 mm. Fil vertical sur les panneaux des colonnes, horizontal sur les panneaux longs et continu sur les deux façades de tiroir.",
    325: "Plateau et chapeaux d’enceintes : chêne européen massif 30 mm, en planches collées sur chant. Si l’on craint le mouvement du bois, panneau latté plaqué 30 mm avec alaise en chêne massif de 30 mm.",
    326: "Chêne massif pour les façades de tiroir, les rebords et la traverse arrière de la tablette, et les plinthes.",
    328: "Finition : chêne naturel clair, sans teinture. Poncer au grain 150/180, deux couches d’Osmo Polyx-Oil 3062 Matt (ou Rubio Monocoat Oil Plus 2C Pure). Finir chaque pièce, y compris le dessous de la tablette, avant l’assemblage final. Quincaillerie noire.",
    329: "Notes de fabrication",
    330: "Construire d’abord les deux colonnes comme des caissons fermés (façade ouverte) de 20 × 50 × 127. Leurs panneaux intérieurs forment les parois latérales de la travée : les percer pour les coulisses de la tablette (partie fixe entre 63 et 68 cm, à 1,5 cm de l’avant) et pour les fixations des panneaux de la travée avant l’assemblage.",
    331: "Relier les colonnes par les panneaux de la travée : panneau bas (face supérieure à 21,8), panneau fixe intermédiaire (face supérieure à 80), plateau (91 à 100) et panneau arrière. Tourillons et colle aux assemblages visibles ; vis Confirmat cachées derrière les tiroirs et la tablette, là où elles ne se verront pas.",
    332: "Le panneau bas de la travée franchit 145 cm sans pied. La séparation des livres est collée et vissée sur toute sa longueur au panneau bas et au panneau arrière, et le panneau arrière est collé le long du chant arrière : ensemble, ils jouent le rôle de raidisseurs. Ne pas ajouter de traverse sous le chant avant ; le dégagement doit rester libre sur 20 cm.",
    333: "Placer le panneau bas de la travée, la séparation des livres et les deux étagères réglables en retrait de 15 cm par rapport au plan avant. Le chant avant du panneau, à 21,8, n’est ni soutenu ni alaisé ; l’alaiser et adoucir ses arêtes, car il est à hauteur des tibias.",
    334: "Le panneau arrière de la travée forme la face arrière du meuble et s’arrête à 91. La goulotte à câbles est la bande de 91 à 97, laissée ouverte derrière les logements d’une colonne à l’autre ; sans panneau au-dessus de 91, sa face arrière est ouverte elle aussi, sur les 145 × 6 cm. Placer la console à 5 cm du mur. C’est par cet écart que la goulotte respire sur toute sa longueur et que les câbles sortent : il fait donc partie de la construction, ce n’est pas une préférence de placement. Voir la coupe et la vue en plan, où il est dessiné et coté.",
    335: "Découper les quatre logements dans le plateau avant la finition, et essayer chaque appareil à blanc avant la pose du bandeau. L’affleurement se règle par les tasseaux : faire les découpes au gabarit des appareils et laisser le réglage des hauteurs de fond pour l’installation.",
    336: "Les logements offrent 9 cm de hauteur libre sous la surface, de 100 jusqu’au fond à 91. C’est la place disponible pour le châssis de chaque appareil sous sa propre plaque supérieure, et non pour sa hauteur hors tout : trois des quatre appareils du tableau du matériel y figurent avec plus de 9 cm, parce que ces chiffres incluent tout ce qui se trouve au-dessus de la plaque supérieure, capot anti-poussière de la platine compris. Mesurer la hauteur sous plaque des quatre appareils avant la découpe, et régler chaque fond de logement en conséquence sur les tasseaux, qui offrent ±10 mm et pas plus.",
    337: "Ne rien obturer avec des joints, du ruban adhésif ou de la mousse. Le jeu de 2 mm sur les côtés et à l’arrière de chaque appareil, les entailles des parois arrière des logements, l’absence de paroi arrière pour la Xone:92, l’arrière ouvert de la goulotte et le jeu de 1 cm sous la porte de la niche constituent toute la ventilation, et la Xone:92 est une table de mixage analogique qui chauffe. Toutes ces ouvertures restent dégagées.",
    338: "Coller les parois latérales des logements sous le plateau avant la pose du bandeau. Chaque pont entre deux logements devient alors une semelle de 30 mm sur deux parois de 60 mm, et c’est cet ensemble qui assure la portée ; un pont de 30 mm seul n’est pas assez rigide pour qu’on s’y appuie.",
    339: "Tablette de clavier : coulisses forte charge à montage latéral au-dessus de la surface de la tablette, vissées dans les rebords en chêne massif (détail A, plan 4). Vérifier l’encombrement réel du clavier et la position de ses connecteurs avant de débiter la tablette et de réaliser la découpe du panneau arrière.",
    340: "Tiroirs sur coulisses sous tiroir, façades rentrantes à fleur, jeux de 2 mm, prise de main fraisée sous le chant supérieur. Débiter les deux façades et la porte de la niche dans une même planche, pour un fil continu. Couper les façades et la porte à 11 cm, et non à la hauteur de la zone de 9,2 cm : les fonds de logement prennent 18 mm au-dessus des corps de tiroir, mais rien ne ferme la face avant à cet endroit, les façades montent donc jusqu’au bandeau à 91. Les 18 mm qui dépassent au-dessus de chaque corps ont de l’air libre derrière eux jusqu’à la traverse avant. Les deux séparations sont entaillées de la même façon sur leurs 5 cm avant.",
    341: "Niche d’alimentation : 24 × 9,2, ses 7 cm arrière ouverts vers le haut sur la goulotte plutôt que vers l’arrière dans une gaine technique. Porte sur charnières invisibles avec ouverture par pression, de 9,8 cm de haut dans l’ouverture de 11 cm, de sorte qu’un jeu de 1 cm reste libre au chant inférieur pour l’air. La multiprise est posée à plat sur le fond de la niche, prises vers le haut. Poser les blocs d’alimentation sur le fond à côté d’elle, vers l’arrière de la niche, entre y = 41,2 et y = 48,2 depuis l’avant : au-delà de cette ligne, les fonds de logement se sont arrêtés et la goulotte ouverte passe au-dessus, la hauteur libre y est donc de 17 cm, jusqu’à la face inférieure de la traverse arrière, à 97, et la hauteur des blocs n’est pas une contrainte. L’important est que rien ne soit empilé sur la multiprise (multiprise plus bloc font environ 12,5 cm et culminent à 92,5, ce qui bute contre un fond de logement à l’avant de la niche et bouche la goulotte à l’arrière), et que la goulotte reste dégagée, car c’est le chemin du câble secteur qui sort par la découpe du panneau arrière (83 à 91, x 80,5 à 104,5). Cette découpe débouche sur le chant supérieur du panneau et se prolonge par l’arrière ouvert de la goulotte. La hauteur n’est critique que pour un bloc poussé à l’avant de la niche, sous un fond de logement : il y a là 9,2 cm de hauteur libre, qu’un bloc de 8,5 cm franchit avec 7 mm de marge.",
    342: "Étagères réglables sur taquets de 5 mm, trous à entraxe de 32 mm. Implanter les deux rangées à partir des faces avant et arrière du compartiment à livres lui-même, à 37 mm de chacune, et non à partir de l’avant du caisson : le compartiment commence 15 cm en retrait, les rangées tombent donc à 18,7 et 44,5 cm derrière la face avant de la console, à 25,8 cm l’une de l’autre. Finir le dessous de la tablette : c’est le plafond des compartiments à livres.",
    343: "Mettre de niveau sur les huit pieds pour que la tablette coulisse droit, puis fixer chaque colonne au mur avec une équerre anti-basculement invisible, calée à 5 cm pour que l’équerre maintienne l’écart au mur au lieu de plaquer la console contre lui.",
    344: "Rendu de principe",
    345: "Vue de synthèse construite à partir de la géométrie des plans (Three.js). Les matériaux, l’éclairage et les détails du matériel sont indicatifs ; les plans font foi.",
    346: "Dossier technique pour le menuisier. Version 2.0 (matériel encastré à fleur), {DATE}. Toutes les cotes sont en centimètres, sauf mention en mm. Chêne naturel clair, huilé mat.",
    347: "Liste de débit pour devis",
    348: "Toutes les pièces de bois à leur cote finie, regroupées selon le matériau dans lequel elles sont débitées, pour qu’un fournisseur ou un menuisier puisse chiffrer le travail sans lire les plans. Cotes en cm, L × l ; épaisseur en mm. « Fil selon L » signale les pièces dont le sens du fil est imposé par le dossier ; les autres peuvent être tournées pour optimiser le débit. Ni surcote d’usinage ni pertes ne sont comptées. La nomenclature reste la référence pour l’assemblage.",
    349: "Totaux",
    350: "Matériau",
    351: "Pièces",
    352: "Quantité nette",
    353: "Contreplaqué bouleau plaqué chêne, 18 mm, placage tranché sur dosse A/B",
    354: "4 plaques de 250 × 125, fil du parement dans le sens des 250. Voir la note ci-dessous.",
    355: "Chêne massif, 30 mm",
    356: "Plateau et chapeaux d’enceintes, en planches collées sur chant.",
    357: "Chêne massif, 50 mm",
    358: "Bandeau du plateau, une pièce de 145 × 6.",
    359: "Chêne massif, 18 mm",
    360: "Façades de tiroir, porte de la niche, plinthes, rebords et traverse de la tablette. Les façades et la porte sont tirées d’une même planche d’au moins 145 × 10,6.",
    361: "Chêne massif, 20 × 14 mm",
    362: "Tasseaux des fonds de logement.",
    363: "Alaise en chêne massif, 5 × 18 mm",
    364: "environ 28 m",
    365: "Contreplaqué bouleau, 15 mm",
    366: "Côtés, devants et arrières des corps de tiroir, cotes nominales.",
    367: "Contreplaqué bouleau, 6 mm",
    368: "Fonds des corps de tiroir, cotes nominales.",
    369: "Total",
    370: "Pièces, plus l’alaise.",
    371: "Pourquoi 4 plaques alors que 7,55 m² tiendraient sur 3 : c’est le fil qui fixe le nombre, pas la surface. Les joues de colonne, le panneau bas de la travée, le panneau fixe intermédiaire, le panneau arrière de la travée et le panneau de la tablette de clavier dépassent chacun la moitié d’une plaque. Chacun doit donc suivre les 250 cm de longueur de la plaque, et deux d’entre eux ne tiennent jamais bout à bout : chaque plaque n’en reçoit qu’une rangée. Côte à côte, ils demandent 394,4 cm, et 3 plaques n’offrent que 375 cm de largeur. Les 39 pièces tiennent sur 4 plaques avec des traits de scie de 4 mm.",
    372: "Contreplaqué bouleau plaqué chêne, 18 mm",
    373: "L × l (cm)",
    374: "Fil selon L. Chant avant alaisé.",
    375: "Chant avant alaisé.",
    376: "Fil selon L.",
    377: "Fil selon L. Deux découpes, voir la nomenclature.",
    378: "Entaillée à 9,2 de haut derrière les 5 cm avant. Chant avant alaisé.",
    379: "Paroi latérale de logement (platine)",
    380: "Paroi latérale de logement (XDJ-700)",
    381: "Paroi latérale de logement (Xone:92)",
    382: "Paroi arrière de logement (platine)",
    383: "Deux pièces par paroi, de part et d’autre de l’entaille de 12 cm pour les câbles.",
    384: "Paroi arrière de logement (XDJ-700)",
    385: "Fond de logement (platine)",
    386: "Fond de logement (XDJ-700)",
    387: "Fond de logement (Xone:92)",
    388: "Fil selon L. Les deux faces sont visibles. Chant avant alaisé.",
    389: "Quatre découpes pour le matériel, voir la vue en plan du plateau (plan 3). En planches collées sur chant, ou panneau plaqué 30 mm avec alaise en chêne de 30 mm.",
    390: "Occupe les 5 cm de la traverse avant sous le plateau, de 91 à 97. Voir le détail B (plan 5).",
    391: "Débiter les deux façades et la porte de la niche à la suite dans une même planche d’au moins 145 × 10,6, pour que le fil se prolonge sur les trois.",
    392: "Dans la même planche que les façades de tiroir.",
    393: "Tasseau de fond de logement (platine)",
    394: "Tasseau de fond de logement (XDJ-700)",
    395: "Tasseau de fond de logement (Xone:92)",
    396: "1,8 de large",
    397: "Contreplaqué bouleau, corps de tiroir",
    398: "Côté de corps de tiroir",
    399: "Devant et arrière de corps de tiroir",
    400: "Cotes nominales, pour le chiffrage : calculées pour un corps aussi large que son ouverture de 58,7 cm. La notice des coulisses fixe la largeur définitive.",
    401: "Fond de corps de tiroir",
    402: "Cotes nominales, comme ci-dessus.",
    403: "Quantités, d’après la liste de débit : 7,55 m² de contreplaqué bouleau plaqué chêne 18 mm, soit 4 plaques de 250 × 125 à cause du sens du fil, 0,93 m² de chêne massif 30 mm pour le plateau et les chapeaux, plus du chêne massif pour le bandeau, les rebords, la traverse de tablette, les façades de tiroir, les plinthes, les tasseaux et les alaises. Le menuisier doit revérifier par rapport à ses propres formats de plaques.",
}

# Per-occurrence wording, keyed by (unit id, occurrence index in document order).
OVERRIDES = {
    # plan: "7 traverse arrière" collides with "36,2 logement le plus profond" on the
    # same dimension chain; the label sits at the rear edge, so "traverse" is unambiguous
    (127, 1): "7 traverse",
}

# Exact substring edits on the drawings; each must match exactly once.
TAG_EDITS = [
    # front elevation: pull the "9 plateau" / "11 façades" pair apart along their dimensions
    ('x="863.0" y="298.0"', 'x="863.0" y="292.0"'),
    ('rotate(-90 863.0 298.0)', 'rotate(-90 863.0 292.0)'),
    ('x="863.0" y="338.0"', 'x="863.0" y="341.0"'),
    ('rotate(-90 863.0 338.0)', 'rotate(-90 863.0 341.0)'),
    # plan: same for "7 traverse" / "36,2 logement le plus profond"
    ('x="847.0" y="89.2"', 'x="847.0" y="90.2"'),
    ('rotate(-90 847.0 89.2)', 'rotate(-90 847.0 90.2)'),
    ('x="847.0" y="175.6"', 'x="847.0" y="182.0"'),
    ('rotate(-90 847.0 175.6)', 'rotate(-90 847.0 182.0)'),
    # widen three canvases for the longer French leaders; drawing scale is unchanged
    # because each SVG keeps its fixed CSS height and only gains empty margin
    ('viewBox="0 0 724 764" width="724"', 'viewBox="-80 0 804 764" width="804"'),
    ('viewBox="0 0 738 379" width="738"', 'viewBox="0 0 800 379" width="800"'),
    ('viewBox="0 0 844 332" width="844"', 'viewBox="0 0 950 332" width="950"'),
]

# French edition type scale, appended to the generated stylesheet. The translation runs
# about 20% longer than the English, so the type steps down slightly to keep the
# English pagination (13 pages, same page breaks).
FR_CSS = """
    body { font-size: 10pt; line-height: 1.36; }
    .muted { font-size: 9pt; }
    table { font-size: 8.6pt; }
    .parts table { font-size: 7.5pt; line-height: 1.32; } .parts th, .parts td { padding: 1.2pt 4pt; }
    .cols table { font-size: 7.6pt; line-height: 1.3; } .cols th, .cols td { padding: 1pt 4pt; }
    """
